apiVersion: v1
kind: Service
metadata:
  namespace: jira
  name: jira
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
spec:
  selector:
    app: jira
  ports:
    - name: "jira"
      port: 8080
      targetPort: 8080
