apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  namespace: jira
  labels:
    app: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - env:
        - name: ATL_JDBC_PASSWORD
          value: admin
        - name: ATL_JDBC_URL
          value: jdbc:postgresql://postgresql:5432/jiradb
        - name: ATL_JDBC_USER
          value: jiradbuser
        - name: JIRA_PROXY_NAME
        - name: JIRA_PROXY_PORT
        - name: JIRA_PROXY_SCHEME
        - name: SETENV_JVM_MAXIMUM_MEMORY
          value: 4096m
        - name: SETENV_JVM_MINIMUM_MEMORY
          value: 2048m
        image: atlassian/jira-software:8.5.4
        imagePullPolicy: "IfNotPresent"
        name: jira
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-data
      volumes:
        - name: jira-data
          hostPath:
            path: /jira/jira_data
            type: Directory
status: {}
