apiVersion: v1
kind: Service
metadata:
  namespace: jira
  name: postgres
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '5432'
spec:
  selector:
    app: postgres
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
